"""change to post table

Revision ID: 2811cdf51200
Revises: ede712510b21
Create Date: 2019-03-09 18:19:34.257469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2811cdf51200'
down_revision = 'ede712510b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('update_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'update_date')
    # ### end Alembic commands ###
