"""another update to post table

Revision ID: 60b5abf08be8
Revises: 2811cdf51200
Create Date: 2019-03-09 18:47:12.574315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b5abf08be8'
down_revision = '2811cdf51200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('current', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_post_current'), 'post', ['current'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_current'), table_name='post')
    op.drop_column('post', 'current')
    # ### end Alembic commands ###
